import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('three media operations use dedicated workspace presentation', async () => {
  const [workspace, css] = await Promise.all([
    readFile(new URL('./media-workspace.js', import.meta.url), 'utf8'),
    readFile(new URL('./media-workspace-ui.css', import.meta.url), 'utf8'),
  ]);

  assert.match(workspace, /data-media-mode="hardsub"/);
  assert.match(workspace, /data-media-mode="transcode"/);
  assert.match(workspace, /data-media-mode="copy"/);
  assert.equal((workspace.match(/data-media-mode="/g) || []).length, 3);

  assert.match(workspace, /硬字幕压制工作区/);
  assert.match(workspace, /纯视频转码工作区/);
  assert.match(workspace, /无损快速剪切工作区/);
  assert.match(workspace, /document\.body\.dataset\.mediaOperation = mode/);
  assert.match(workspace, /const runButtonLabel = \(\) => get\('operation'\)\.value==='hardsub'\?'使用当前参数开始硬压':get\('operation'\)\.value==='transcode'\?'开始视频转码':'开始无损剪切'/);
  assert.match(workspace, /id="taskPlanSummary"/);
  assert.equal((workspace.match(/id="taskPlanSummary"/g) || []).length, 1);
  assert.ok(workspace.indexOf('id="taskPlanSummary"') < workspace.indexOf('id="taskEncoding"'), 'plan summary must precede detailed encoding controls');
  assert.match(workspace, /核心视频方案/);
  assert.match(workspace, /恢复推荐方案/);
  assert.match(workspace, /验证当前方案/);
  assert.match(workspace, /通常越低越保真/);
  assert.match(workspace, /presetIntent\(get\('encoder'\)\.value,v\)/);
  assert.match(workspace, /media-video-details/);
  assert.match(workspace, /轨道保留/);
  assert.match(workspace, /<strong>音频与封装<\/strong>/);
  assert.match(workspace, /select\('audio','音频策略'/);
  assert.match(workspace, /outputPolicy\?\.querySelectorAll\('\[name\]'\)\.forEach\(control => control\.setAttribute\('form','mediaTaskForm'\)\)/);
  assert.match(workspace, /id="taskOutputPolicy"/);
  assert.match(workspace, /select\('outputContainer','成品容器'/);
  assert.match(workspace, /Auto · 自动选择安全容器/);
  assert.match(workspace, /保持源容器/);
  assert.match(workspace, /共享出口/);
  assert.match(workspace, /data-operation-branch="hardsub"/);
  assert.match(workspace, /data-operation-branch="transcode"/);
  assert.match(workspace, /data-operation-branch="copy"/);
  assert.match(workspace, /id="taskNvencDetails"/);
  assert.match(workspace, /id="taskRunState"/);
  assert.match(workspace, /id="taskPercent"/);
  assert.match(workspace, /id="taskSave"/);
  assert.match(workspace, /save_failed/);
  assert.match(workspace, /task-technical-details/);
  assert.match(workspace, /id="taskWaveformPanel"/);
  assert.match(workspace, /id="taskWaveformTrack"/);
  assert.match(workspace, /id="taskWaveformSetStart"/);
  assert.match(workspace, /id="taskWaveformSetEnd"/);
  assert.match(workspace, /id="taskWaveformRuler"/);
  assert.match(workspace, /id="taskKeyframeLane"/);
  assert.match(workspace, /id="taskWaveformActualStart"/);
  assert.match(workspace, /id="taskCopyBoundaryInfo"/);
  assert.match(workspace, /id="taskKeyframeSnapStart"/);
  assert.match(workspace, /includeKeyframes:copy/);
  assert.match(workspace, /previousKeyframe/);
  assert.match(workspace, /实际无损起点/);
  assert.match(workspace, /MM:SS\.mmm/);
  assert.match(workspace, /parseMediaTime/);
  assert.match(workspace, /formatMediaTimeInput/);
  assert.match(workspace, /hooks\.waveform/);

  assert.match(workspace, /class="media-mode-explainer media-mode-explainer-hardsub"/);
  assert.match(workspace, /class="media-mode-explainer media-mode-explainer-transcode"/);
  assert.match(workspace, /class="media-mode-explainer media-mode-explainer-copy"/);
  assert.match(workspace, /data-hardsub-strategy/);
  assert.match(workspace, /hardsub-control-strategy-v1/);
  assert.match(workspace, /syncHardsubStrategyChrome/);
  assert.match(workspace, /section\.dataset\.mobileStageSection = hardsub \? 'produce' : 'prepare'/);
  assert.match(workspace, /hooks\.onModeChange\?\.\(mode\)/);
  assert.match(workspace, /hardsub-strategy-suppressed/);
  assert.match(workspace, /HARDSUB · PARAMETERS/);
  assert.match(workspace, /使用当前参数开始硬压/);

  assert.match(workspace, /qualityRange\.type = 'range'/);
  assert.match(workspace, /className = 'media-inline-range'/);
  assert.match(workspace, /qualityRange\.addEventListener\('input'/);
  assert.match(workspace, /function setRateControl\(key, active\)/);
  assert.match(workspace, /owner\.hidden=!active/);
  assert.match(workspace, /setRateControl\('quality', !copy && mode==='quality'\)/);
  assert.match(workspace, /setRateControl\('bitrate', !copy && mode==='bitrate'\)/);
  assert.match(workspace, /\['targetSize','sizeUnit','sizeReserve'\]\)setRateControl\(key, !copy && mode==='size'\)/);

  assert.match(css, /\.media-mode-switcher\s*\{/);
  assert.match(css, /\.media-branch-map\s*\{/);
  assert.match(css, /\.media-operation-branch\s*\{/);
  assert.match(css, /\.media-output-policy\s*\{/);
  assert.match(css, /button\[aria-pressed="true"\]/);
  assert.match(css, /body\[data-media-operation="transcode"\] \.production-region/);
  assert.match(css, /body\[data-media-operation="copy"\] \.media-encoding-panel/);
  assert.match(css, /body\[data-media-operation="copy"\] \.media-sample-panel/);
  assert.match(css, /\.media-inline-range::-webkit-slider-runnable-track/);
  assert.match(css, /\.media-action-dock\s*\{/);
  assert.match(css, /\.media-waveform-panel\s*\{/);
  assert.match(css, /\.media-waveform-track\s*\{/);
  assert.match(css, /\.media-waveform-boundary/);
  assert.match(css, /\.media-waveform-ruler/);
  assert.match(css, /\.media-keyframe-lane/);
  assert.match(css, /\.media-keyframe-mark/);
  assert.match(css, /\.media-waveform-actual-start/);
  assert.match(css, /\.media-copy-boundary-info/);
  assert.match(css, /#taskSave\.task-primary-action/);
  assert.match(css, /#taskRun\.task-secondary-action/);
  assert.match(css, /\.task-progress-grid/);
  assert.match(css, /\.task-plan-actions/);
  assert.match(css, /\.media-advanced-panel\[hidden\]/);
  assert.match(css, /\.media-workspace \.task-grid input:disabled/);
  assert.match(css, /\.media-workspace \.task-grid select:disabled/);
  assert.equal((css.match(/\{/g) || []).length, (css.match(/\}/g) || []).length);
});
