import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('web shell keeps platform guidance but uses compact native workbench layout', async () => {
  const [main, css] = await Promise.all([
    readFile(new URL('./main.js', import.meta.url), 'utf8'),
    readFile(new URL('./style.css', import.meta.url), 'utf8'),
  ]);

  assert.match(main, /id="windowsNativeCard"/);
  assert.match(main, /WINDOWS NATIVE/);
  assert.match(main, /id="nativeStatusBar"/);
  assert.match(main, /renderNativeStatusBar/);
  assert.match(main, /nativeGpuLabel/);
  assert.match(main, /id="videoNativePickerBtn"/);
  assert.match(main, /id="assNativePickerBtn"/);
  assert.match(main, /id="fontsNativePickerBtn"/);
  assert.match(main, /id="videoWebPicker" class="file-picker-trigger"/);
  assert.match(main, /id="assWebPicker" class="file-picker-trigger"/);
  assert.match(main, /id="fontsWebPicker" class="file-picker-trigger"/);
  assert.match(main, /requestWindowsNativePicker/);
  assert.match(main, /nativePlatformName\(\) \+ ' 自检：'/);
  assert.match(main, /class="workspace-layout"/);
  assert.match(main, /class="platform-rail"/);
  assert.match(main, /class="adaptive-region setup-region"/);
  assert.match(main, /class="adaptive-region production-region"/);
  assert.match(main, /class="production-controls"/);
  assert.match(main, /function resolveWindowSizeClass\(width = window\.innerWidth\)/);
  assert.doesNotMatch(main, /data-theme-choice=/);
  assert.doesNotMatch(main, /THEME_KEY/);
  assert.doesNotMatch(main, /prefers-color-scheme/);
  assert.match(main, /HARDSUB WORKBENCH/);
  assert.match(main, /<h1>硬字幕压制<\/h1>/);
  assert.match(main, /class="app-header-main"/);
  assert.match(main, /largeMax:\s*1599/);
  assert.match(main, /return 'extra-large'/);

  assert.match(css, /\.workspace-layout\s*\{\s*display:\s*block/);
  assert.match(css, /\.windows-native-connected \.platform-rail\s*\{\s*display:\s*none/);
  assert.match(css, /\.native-status-bar\s*\{/);
  assert.match(css, /data-window-size="medium"\] \.input-card > \.grid\.two\s*\{\s*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.native-picker-button\s*\{/);
  assert.match(css, /\.file-input-control\s*\{/);
  assert.match(css, /\.file-picker-trigger,/);
  assert.match(css, /\.status-list\s*\{[\s\S]*?repeat\(auto-fit, minmax\(205px, 1fr\)\)/);
  assert.match(css, /\.preview-wrap\s*\{[\s\S]*?max-width:\s*760px/);
  assert.match(main, /<details class="card log-card">/);
  assert.match(main, /id="previewLightbox" class="preview-lightbox"/);
  assert.match(main, /id="mobileStageNav" class="mobile-stage-nav"/);
  assert.match(main, /data-mobile-stage-target="prepare"/);
  assert.match(main, /data-mobile-stage-target="produce"/);
  assert.equal((main.match(/data-mobile-stage-target="/g) || []).length, 2);
  assert.match(main, /function devicePrefersMobileShell\(\)/);
  assert.match(main, /document\.body\.classList\.toggle\('ui-mobile', mobile\)/);
  assert.match(main, /function setMobileStage\(stage/);
  assert.match(css, /body\.ui-desktop \.production-region/);
  assert.match(css, /body\.ui-mobile \.mobile-stage-nav/);
  assert.match(css, /body\.ui-mobile \[data-mobile-stage-section\]/);
  assert.match(css, /body\.ui-mobile\[data-mobile-stage="prepare"\]/);
  assert.match(css, /body\.ui-mobile\[data-mobile-stage="produce"\]/);
  assert.match(main, /detectBasicCapabilities/);
  assert.match(main, /data-workflow-step="prepare"/);
  assert.match(main, /data-workflow-step="produce"/);
  assert.equal((main.match(/data-workflow-step="/g) || []).length, 2);
  assert.match(main, /function ensureWebEngineReady\(\)/);
  assert.match(main, /function ensureNativeSelfTestStarted\(\)/);
  assert.match(main, /首张真实预览已成功解码输入视频/);
  assert.match(main, /id="continueToProduceBtn"/);
  assert.match(main, /mobile-stage-copy/);
  assert.match(main, /预览与压制/);
  assert.match(css, /Mobile task shell v2/);
  assert.match(css, /body\.ui-mobile \.mobile-preflight-action/);
  assert.match(css, /body\.ui-mobile \.mobile-stage-nav \{/);
  assert.match(main, /class="mobile-runtime-help"/);
  assert.match(main, /class="mobile-runtime-option android"/);
  assert.match(main, /class="mobile-runtime-option windows"/);
  assert.match(css, /--mobile-sky: #55b9ff/);
  assert.match(css, /--mobile-grass: #72d66c/);
  assert.match(main, /class="platform-guide"/);
  assert.match(main, /windows\/start_windows\.bat/);
  assert.match(main, /下载最新版 APK/);
  assert.match(css, /Native setup guides/);
  assert.match(css, /body\.ui-mobile \.mobile-runtime-help/);
  assert.doesNotMatch(main, /执行输入解码 smoke test/);
  assert.match(main, /id="previewZoom"/);
  assert.match(main, /class="preview-image"/);
  assert.match(css, /\.preview-lightbox\s*\{/);
  assert.match(css, /\.preflight-card \.status-list\s*\{[\s\S]*?display:\s*flex/);
  assert.doesNotMatch(main, /data-range-step="quick"/);
  assert.doesNotMatch(main, /data-range-reset="quick"/);

  assert.match(main, /selectedTests:\s*\{\}/);
  assert.match(main, /function restoreSelectedTestForCurrentPlan\(\)/);
  assert.match(main, /function selectedTestCacheKey\(codec, plan\)/);
  const selectStart = main.indexOf('function selectCodec(codec)');
  const selectEnd = main.indexOf('function qualityCrfRange', selectStart);
  assert.ok(selectStart > 0 && selectEnd > selectStart);
  const selectBlock = main.slice(selectStart, selectEnd);
  assert.doesNotMatch(selectBlock, /state\.selectedTest\s*=\s*null/);
  assert.doesNotMatch(selectBlock, /revokeObjectURL/);
  assert.match(main, /id="nextP" type="button"/);
  assert.match(main, /const targetFrames = testCodec === 'av1' \? 120 : 72/);
  assert.match(main, /const maxSampleSeconds = testCodec === 'av1' \? 4\.0 : 2\.4/);
  assert.match(main, />下一条<\/button>/);

  assert.match(main, /data-plan-mode="quick"/);
  assert.match(main, /data-plan-mode="quality"/);
  assert.match(main, /data-plan-mode="size"/);
  assert.match(main, /id="quickPresetRange" class="plan-slider plan-interaction" type="range"/);
  assert.match(main, /id="qualityTargetRange" class="plan-slider plan-interaction" type="range"/);
  assert.match(main, /id="sizeBudgetRange" class="plan-slider plan-interaction" type="range"/);
  assert.match(main, /id="qualityAutoCodec"/);
  assert.match(main, /id="sizeBudgetMultiplier" type="hidden"/);
  assert.match(main, /function commitQualityTarget\(\)/);
  assert.match(main, /function commitSizeBudget\(\)/);
  assert.match(main, /parseLibassFontDiagnostics/);
  assert.match(main, /renderRuntimeFontDiagnostics/);
  assert.match(main, /previewFontDiagnostics/);
  assert.match(main, /findGlyphRiskPreviewTimes/);
  assert.match(main, /buildPreviewPlan/);
  assert.match(main, /mergePreviewTimes/);
  assert.match(main, /previewRiskTimes/);
  assert.match(main, /goal !== 'sizeBudget'/);
  assert.doesNotMatch(main, /<option value="quality">质量优先/);
  assert.doesNotMatch(main, /体积预算：1\.6×/);
  assert.match(main, /诊断：固定参数编码器基准测试/);
  assert.match(css, /\.plan-mode-tabs\s*\{/);
  assert.match(css, /\.plan-slider::-webkit-slider-runnable-track/);
  assert.match(css, /--slider-progress/);
  assert.match(css, /\.runtime-font-diagnostics\s*\{/);
  assert.match(css, /\.runtime-font-row\s*\{/);
  assert.match(css, /Current dark workbench/);
  assert.match(css, /Current adaptive window layout/);
  assert.match(css, /@layer foundation, current;/);
  assert.match(css, /@layer foundation\s*\{/);
  assert.match(css, /@layer current\s*\{/);
  assert.doesNotMatch(css, /Adaptive window-size workbench v5/);
  assert.doesNotMatch(css, /Semantic contrast \+ adaptive theme v2/);
  assert.doesNotMatch(css, /Compact workbench layout v3/);
  assert.doesNotMatch(css, /Relaxed desktop workbench v4/);
  assert.doesNotMatch(css, /Modern dark workbench v6/);
  assert.doesNotMatch(css, /Adaptive workbench v7/);
  assert.match(css, /data-window-size="expanded"\] \.production-region\s*\{[\s\S]*?display:\s*grid/);
  assert.match(css, /data-window-size="large"\] \.production-region,[\s\S]*?display:\s*grid/);
  assert.equal((css.match(/\{/g) || []).length, (css.match(/\}/g) || []).length);
  assert.match(css, /data-window-size="compact"\] \.setup-region/);
  assert.match(css, /data-window-size="medium"\] \.production-region/);
  assert.doesNotMatch(css, /System may still resolve\s+to light/);
});


test('desktop and mobile use the exact same canonical task shell', async () => {
  const main = await readFile(new URL('./main.js', import.meta.url), 'utf8');

  assert.match(main, /function devicePrefersMobileShell\(\) \{[\s\S]*return true;/);
  assert.match(main, /document\.body\.classList\.add\('ui-mobile'\)/);
  assert.match(main, /document\.body\.classList\.remove\('ui-desktop'\)/);
  assert.match(main, /document\.documentElement\.dataset\.uiShell = 'mobile'/);
});
